### ISSUE TITLE
[ASK] Why isn't the full App Code published?

### ISSUE THREAD

**Issue by edgarchinchilla** [YerongAI/Office-Tool#340] opened 2021-09-16 20:56 UTC
**Question:**
> Write down here
I've looking around the repo to "Compile the App by myself" but not all the code is published... There is a reason behind?

**Comment by YerongAI** [comment] 2021-09-17 01:45
You don't need to compile it by yourself, our application is signed and secured.

And we don't want to publish all source code here, no reasons.

**Comment by edgarchinchilla** [comment] 2021-09-17 02:21
Thanks for the response... I really appreciate your Work, the App is Awesome, howeber, as you know, many of us in the "Open Source World" preffer to compile from sources, learn from the code and also if possible, contribute with features/fixes.

Would be great if you publish all the source code to really commit with the "Open Source" community, or publish the sources in your website if you prefer.

Regards.

**Comment by YerongAI** [comment] 2021-09-17 03:47
> Thanks for the response... I really appreciate your Work, the App is Awesome, howeber, as you know, many of us in the "Open Source World" preffer to compile from sources, learn from the code and also if possible, contribute with features/fixes.
> 
> Would be great if you publish all the source code to really commit with the "Open Source" community, or publish the sources in your website if you prefer.
> 
> Regards.

Thanks for your suggestions, but we can't publish all source code due to some reasons.

If you find any issues or problems, please let us know and we will fix/improve it ASAP.

**Comment by YerongAI** [comment] 2021-09-20 06:10
The issue is not responding so we will close it now.

If any questions please reopen it or open a new issue for help.

**Comment by elovelan** [comment] 2021-10-06 14:25
Consider adding a note to the README explaining the reasons. The open source community is generally very understanding so clarifying "some reasons" would be appreciated!

**Comment by edgarchinchilla** [comment] 2021-10-06 14:47
That would be good @elovelan , @YerongAI , do not misunderstand us, we love your App, is very usefull, but if you says in the main portal that the App is "Open Source" that was not really true... You would consider adding a note in the main site and in the README of the repo to clarify that the app is "partially" open source...

**Comment by inliquid** [comment] 2022-08-27 21:44
Source code needed not only to be able to learn and contribute it also needed to analyze and prove that the app is safe, and is not a malware/trojan or something similar. Having a/v which does not detect it as a virus/trojan or other malicious software does not mean anything. In particular it does not mean that the app is safe. Nobody should trust this publisher who "has reasons" for not providing compilable source code.

**Comment by edgarchinchilla** [comment] 2022-08-29 12:56
@YerongAI, you shouldn't use the "Open Source" label for your App in your main app website, because the app isn't open source right now.

**Comment by YerongAI** [comment] 2022-08-29 14:04
> Source code needed not only to be able to learn and contribute it also needed to analyze and prove that the app is safe, and is not a malware/trojan or something similar. Having a/v which does not detect it as a virus/trojan or other malicious software does not mean anything. In particular it does not mean that the app is safe. Nobody should trust this publisher who "has reasons" for not providing compilable source code.

We are very sorry, we cannot upload our source code. Releasing the source code exposes our program to the problem of resale and copyright infringement, which is very annoying.

Our program is signed to prevent it from being tampered with. If you don't think that's enough, then we respect your choice.

**Comment by elovelan** [comment] 2022-08-29 14:10
> We are very sorry, we cannot upload our source code. Releasing the source code exposes our program to the problem of resale and copyright infringement, which is very annoying.

You can use a license that prevents this. Not only will any bad actors be legally liable for copyright infringement but you can also receive monetary compensation for any violations.

**Comment by YerongAI** [comment] 2022-08-31 14:02
> You can use a license that prevents this. Not only will any bad actors be legally liable for copyright infringement but you can also receive monetary compensation for any violations.

This is hard to do if there are a lot of bad actors doing this. And I don't want to waste my time on this.

**Comment by YerongAI** [comment] 2022-08-31 14:04
Anyway, open source is a great way to share ideas and suggestions, but it doesn't apply to me. So I won't be uploading the full source code for Office Tool Plus.

**Closed by YerongAI** 2022-08-31 14:04 UTC
Labels: help wanted, good first issue
