### ISSUE TITLE
[BUG] Unable to create new guard page for stack.

### ISSUE THREAD

**Issue by boromyr** [YerongAI/Office-Tool#574] opened 2022-12-02 18:11 UTC
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10 beta

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 22000

**Error description (required):**
> Errore durante l'avvio della versione OT 10
Unable to create new guard page for stack.
![image](https://user-images.githubusercontent.com/52782032/205357646-4a798d7e-46b0-4c78-b739-1561248f0e6e.png)

**Comment by iDolmatov** [comment] 2022-12-02 18:32
Beta? GitHub Release only [Alpha](https://github.com/YerongAI/Office-Tool/releases/tag/v10.0.0.4) (Pre-release).

**Comment by boromyr** [comment] 2022-12-02 18:34
Sorry, careless error, I meant alpha version, the last one released today

**Comment by iDolmatov** [comment] 2022-12-02 18:45
There is little information on this error. Please try to provide more details.
1. Installed .net? What versions, varieties?
2. Is the package used with or without runtime?
3. Is the latest release running?
4. RAM memory and swap file have free space?
5. Have you rebooted your PC?

Try to get the debug log. 

> Maybe you can launch "Office Tool Plus.Console" with argument "/enableLog" to see the details.

I recommend using output to a text file in the console/terminal. An example is below, but you need to specify your own paths to the files.

`"C:\Office Tool\Office Tool Plus.Console.exe" /enableLog >> "C:\Office Tool\OTP_log.txt"`

**Comment by iDolmatov** [comment] 2022-12-02 18:58
**Warning**. Perhaps the problem is related to the system language.

> Known issue: Application can not launch when your OS language is not English or Chinese.
> ——————
> 已知问题：程序无法在非中文或英文系统上启动，因为其匹配不到语言导致进入了一个死循环。

**Comment by YerongAI** [comment] 2022-12-03 05:22
Before we release a new version, you can run this command to fix the problem.

``` batch
reg add HKCU\Software\OfficeToolPlus /f /v Language /d "en-us"
```

**Comment by iDolmatov** [comment] 2022-12-03 13:19
[Office Tool Plus v10.0.0.5 Alpha](https://github.com/YerongAI/Office-Tool/releases/tag/v10.0.0.5)
Check again.

**Comment by boromyr** [comment] 2022-12-03 14:08
I agree that v10.0.0.5 Alpha works correctly, at least for Windows 11 it-IT

**Comment by YerongAI** [comment] 2022-12-03 15:15
> I agree that v10.0.0.5 Alpha works correctly, at least for Windows 11 it-IT

Ok, then we can close the issue now, right?

**Closed** 2022-12-04 07:08 UTC
Labels: bug
